version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "micrologx-devops"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uexiz4tivlx0"
s3_prefix = "micrologx-devops"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
